# Generated by Django 2.2 on 2019-05-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher', models.CharField(blank=True, max_length=120, null=True)),
                ('marketing', models.CharField(blank=True, max_length=120, null=True)),
                ('batch', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
