# Generated by Django 2.2 on 2019-05-01 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='marketing',
            new_name='marketingservices',
        ),
    ]
