# Generated by Django 2.2 on 2019-05-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('author', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher', models.CharField(blank=True, max_length=120, null=True)),
                ('sales_rank', models.CharField(blank=True, max_length=120, null=True)),
                ('page', models.CharField(blank=True, max_length=120, null=True)),
                ('pages', models.CharField(blank=True, max_length=120, null=True)),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.CharField(blank=True, max_length=120, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=120, null=True)),
                ('asin', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.CharField(blank=True, max_length=120, null=True)),
                ('keyword', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
